[package]
name = "depres"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.6"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
comfy-table = "7.1.1"
clap = { version = "4.5.16", features = ["derive"] }
